// AUTO-GENERATED by scripts/optimize-media.mjs — do not edit by hand.
// Regenerate with: pnpm media

export type MediaKind = 'exterior' | 'interior' | 'amenity' | 'location' | 'plan' | 'masterplan';

export interface MediaVariant {
  readonly format: 'avif' | 'webp';
  readonly width: number;
  readonly height: number;
  readonly src: string;
}

export interface MediaAsset {
  readonly id: MediaId;
  readonly kind: MediaKind;
  /** Meaningful alternative text, written per asset. */
  readonly alt: string;
  /** Human caption shown in the gallery lightbox. */
  readonly caption: string;
  /** Provenance of the original file, for audit and rights tracking. */
  readonly source: string;
  /** Eagerly loaded and preloaded when true. */
  readonly priority: boolean;
  /** Included in the cinematic project gallery when true. */
  readonly gallery: boolean;
  readonly width: number;
  readonly height: number;
  /** Inlined blurred preview used to avoid a flash of empty space. */
  readonly lqip: string;
  readonly variants: readonly MediaVariant[];
}

export type MediaId = 'hero' | 'overview-aerial' | 'interior-living' | 'interior-bedroom' | 'interior-lounge' | 'interior-kitchen' | 'amenity-golf' | 'amenity-retail' | 'amenity-wellness' | 'amenity-offices' | 'amenity-clubhouse' | 'exterior-evening' | 'exterior-walkway' | 'exterior-entrance' | 'exterior-facade' | 'exterior-sunset' | 'location-aerial' | 'location-masterplan' | 'location-tbilisi-street' | 'location-tbilisi-city' | 'plan-studio' | 'plan-1br' | 'plan-2br' | 'closing';

export const MEDIA: Readonly<Record<MediaId, MediaAsset>> = {
  "hero": {
    "id": "hero",
    "kind": "exterior",
    "alt": "Dusk render of the Trussardi Residences building at Mira Verde, its illuminated terraces set against the wooded Tbilisi Hills.",
    "caption": "Trussardi Residences — exterior render at dusk",
    "source": "https://mira-verde.com/",
    "priority": true,
    "gallery": false,
    "width": 2100,
    "height": 1568,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoUAA8APwlwr0+rpqQiMAgBcCEJYwCdMoABbzZczRjWPjgAyybjDC9RxT9KBObUM5sa+FwHDU6YVCE0v9M+PxNF9uIq6kxs1AAAAA==",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 314,
        "src": "/media/hero-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 314,
        "src": "/media/hero-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 478,
        "src": "/media/hero-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 478,
        "src": "/media/hero-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 717,
        "src": "/media/hero-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 717,
        "src": "/media/hero-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 956,
        "src": "/media/hero-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 956,
        "src": "/media/hero-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 1195,
        "src": "/media/hero-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 1195,
        "src": "/media/hero-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1434,
        "src": "/media/hero-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1434,
        "src": "/media/hero-1920.webp"
      },
      {
        "format": "avif",
        "width": 2100,
        "height": 1568,
        "src": "/media/hero-2100.avif"
      },
      {
        "format": "webp",
        "width": 2100,
        "height": 1568,
        "src": "/media/hero-2100.webp"
      }
    ]
  },
  "overview-aerial": {
    "id": "overview-aerial",
    "kind": "exterior",
    "alt": "Aerial render of the Mira Verde masterplan terracing down a forested hillside with the city of Tbilisi spread out beyond.",
    "caption": "Mira Verde masterplan above Tbilisi — aerial render",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1069,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAwCdASoUAAsAPwlwsVArpiSisAgBcCEJZQAAW54uueobfPhrXIAA/nO7kCUBBeoB4YbNfQDziwmqDv4PGqyAAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 234,
        "src": "/media/overview-aerial-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 234,
        "src": "/media/overview-aerial-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 356,
        "src": "/media/overview-aerial-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 356,
        "src": "/media/overview-aerial-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 535,
        "src": "/media/overview-aerial-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 535,
        "src": "/media/overview-aerial-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 713,
        "src": "/media/overview-aerial-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 713,
        "src": "/media/overview-aerial-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 891,
        "src": "/media/overview-aerial-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 891,
        "src": "/media/overview-aerial-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1069,
        "src": "/media/overview-aerial-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1069,
        "src": "/media/overview-aerial-1920.webp"
      }
    ]
  },
  "interior-living": {
    "id": "interior-living",
    "kind": "interior",
    "alt": "Trussardi Casa furnished living room with curved cream sofa, tan armchair and floor-to-ceiling glazing framing the hillside.",
    "caption": "Living area, furnished by Trussardi Casa — interior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1059,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAAsAPwlurk+rpiQiMAgBcCEJYwC7AB3LwCKTjEmMAP3STCAf3fPL7hpn++DdZsyjPT9p/iqXiWooKHTaAAAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 232,
        "src": "/media/interior-living-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 232,
        "src": "/media/interior-living-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 353,
        "src": "/media/interior-living-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 353,
        "src": "/media/interior-living-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 530,
        "src": "/media/interior-living-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 530,
        "src": "/media/interior-living-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 706,
        "src": "/media/interior-living-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 706,
        "src": "/media/interior-living-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 882,
        "src": "/media/interior-living-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 882,
        "src": "/media/interior-living-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1059,
        "src": "/media/interior-living-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1059,
        "src": "/media/interior-living-1920.webp"
      }
    ]
  },
  "interior-bedroom": {
    "id": "interior-bedroom",
    "kind": "interior",
    "alt": "Bedroom with a low platform bed and wraparound glazing looking over the Tbilisi valley at daybreak.",
    "caption": "Bedroom with panoramic outlook — interior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1059,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAAsAPwlwr1ArpqQisAgBcCEJZQCdMoADR1tKmNxfVAAA/pQDGMA2YoHP7YL52SCdNaxw/pXglTRReIZ9dJPhb6rW/yl8KhH3AAAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 232,
        "src": "/media/interior-bedroom-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 232,
        "src": "/media/interior-bedroom-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 353,
        "src": "/media/interior-bedroom-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 353,
        "src": "/media/interior-bedroom-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 530,
        "src": "/media/interior-bedroom-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 530,
        "src": "/media/interior-bedroom-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 706,
        "src": "/media/interior-bedroom-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 706,
        "src": "/media/interior-bedroom-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 882,
        "src": "/media/interior-bedroom-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 882,
        "src": "/media/interior-bedroom-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1059,
        "src": "/media/interior-bedroom-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1059,
        "src": "/media/interior-bedroom-1920.webp"
      }
    ]
  },
  "interior-lounge": {
    "id": "interior-lounge",
    "kind": "interior",
    "alt": "Open-plan lounge with sculptural seating and full-height windows overlooking the golf course greens.",
    "caption": "Lounge overlooking the golf course — interior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1072,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABwAwCdASoUAAsAPwlysFArpySisAgBcCEJYwCdMoABCKkYMcAA/c0srXAInotV2Joce2eeHjknO5usBx1nXNjWUVQLkcAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 235,
        "src": "/media/interior-lounge-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 235,
        "src": "/media/interior-lounge-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 357,
        "src": "/media/interior-lounge-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 357,
        "src": "/media/interior-lounge-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 536,
        "src": "/media/interior-lounge-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 536,
        "src": "/media/interior-lounge-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 715,
        "src": "/media/interior-lounge-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 715,
        "src": "/media/interior-lounge-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 893,
        "src": "/media/interior-lounge-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 893,
        "src": "/media/interior-lounge-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1072,
        "src": "/media/interior-lounge-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1072,
        "src": "/media/interior-lounge-1920.webp"
      }
    ]
  },
  "interior-kitchen": {
    "id": "interior-kitchen",
    "kind": "interior",
    "alt": "Furnished open-plan kitchen and dining space with integrated appliances and a terrace beyond the glazing.",
    "caption": "Kitchen and dining, integrated appliances — interior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1059,
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAwCdASoUAAsAPwlysVArpqSisAgBcCEJYwCdABGvSTVU1AAA/FyMTW9kneaDtFH/7EgzM9Tgo1zx5KAwgQAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 232,
        "src": "/media/interior-kitchen-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 232,
        "src": "/media/interior-kitchen-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 353,
        "src": "/media/interior-kitchen-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 353,
        "src": "/media/interior-kitchen-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 530,
        "src": "/media/interior-kitchen-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 530,
        "src": "/media/interior-kitchen-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 706,
        "src": "/media/interior-kitchen-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 706,
        "src": "/media/interior-kitchen-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 882,
        "src": "/media/interior-kitchen-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 882,
        "src": "/media/interior-kitchen-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1059,
        "src": "/media/interior-kitchen-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1059,
        "src": "/media/interior-kitchen-1920.webp"
      }
    ]
  },
  "amenity-golf": {
    "id": "amenity-golf",
    "kind": "amenity",
    "alt": "Golf green beside water at low sun, with a player putting and a buggy on the fairway.",
    "caption": "18-hole golf course — amenity render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1282,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoUAA0APwlurk+rpiQiMAgBcCEJaAC06BZp8oHJagg4AAD+6tv9pJr1B6qK0LYBRWLulpyXh3W9o8GfCS4yUxUWLJeW9DgA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 280,
        "src": "/media/amenity-golf-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 280,
        "src": "/media/amenity-golf-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 427,
        "src": "/media/amenity-golf-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 427,
        "src": "/media/amenity-golf-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 641,
        "src": "/media/amenity-golf-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 641,
        "src": "/media/amenity-golf-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 855,
        "src": "/media/amenity-golf-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 855,
        "src": "/media/amenity-golf-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 1068,
        "src": "/media/amenity-golf-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 1068,
        "src": "/media/amenity-golf-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1282,
        "src": "/media/amenity-golf-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1282,
        "src": "/media/amenity-golf-1920.webp"
      }
    ]
  },
  "amenity-retail": {
    "id": "amenity-retail",
    "kind": "amenity",
    "alt": "Terraced retail and dining promenade at sunset with people walking between glazed storefronts.",
    "caption": "Retail and dining promenade — amenity render",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 2100,
    "height": 1172,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAAsAPwlwr0+rpqQiMAgBcCEJYwCdABr9qweDqRAAAP6DG2LJezaEAv820wY4OrBHdTREZcxJoTnzGuZWJfIAAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 234,
        "src": "/media/amenity-retail-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 234,
        "src": "/media/amenity-retail-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 357,
        "src": "/media/amenity-retail-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 357,
        "src": "/media/amenity-retail-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 536,
        "src": "/media/amenity-retail-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 536,
        "src": "/media/amenity-retail-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 714,
        "src": "/media/amenity-retail-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 714,
        "src": "/media/amenity-retail-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 893,
        "src": "/media/amenity-retail-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 893,
        "src": "/media/amenity-retail-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1072,
        "src": "/media/amenity-retail-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1072,
        "src": "/media/amenity-retail-1920.webp"
      },
      {
        "format": "avif",
        "width": 2100,
        "height": 1172,
        "src": "/media/amenity-retail-2100.avif"
      },
      {
        "format": "webp",
        "width": 2100,
        "height": 1172,
        "src": "/media/amenity-retail-2100.webp"
      }
    ]
  },
  "amenity-wellness": {
    "id": "amenity-wellness",
    "kind": "amenity",
    "alt": "Wellness pavilion beside a reflecting pool catching the last of the sunset.",
    "caption": "Wellness pavilion — amenity render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1434,
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAA8APwlwr0+rpqQiMAgBcCEJQBOmUGUgCBjRPQuFNOCAANq6nek0E71hB8u0zH5u8o8roFPzx80RKSxitIoT4VbHrfzZ+AA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 314,
        "src": "/media/amenity-wellness-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 314,
        "src": "/media/amenity-wellness-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 478,
        "src": "/media/amenity-wellness-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 478,
        "src": "/media/amenity-wellness-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 717,
        "src": "/media/amenity-wellness-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 717,
        "src": "/media/amenity-wellness-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 956,
        "src": "/media/amenity-wellness-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 956,
        "src": "/media/amenity-wellness-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 1195,
        "src": "/media/amenity-wellness-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 1195,
        "src": "/media/amenity-wellness-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1434,
        "src": "/media/amenity-wellness-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1434,
        "src": "/media/amenity-wellness-1920.webp"
      }
    ]
  },
  "amenity-offices": {
    "id": "amenity-offices",
    "kind": "amenity",
    "alt": "Multi-level workplace and community building with planted terraces under a pink evening sky.",
    "caption": "Workplaces and community building — amenity render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1919,
    "height": 1057,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAwCdASoUAAsAPwlwr1ArpqQisAgBcCEJQBOgA4OsQOpBmmoAAP6pjMfJRu9arijoV9l78mO/WfhRRRSj0DWpb906UgdjUAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 231,
        "src": "/media/amenity-offices-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 231,
        "src": "/media/amenity-offices-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 353,
        "src": "/media/amenity-offices-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 353,
        "src": "/media/amenity-offices-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 529,
        "src": "/media/amenity-offices-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 529,
        "src": "/media/amenity-offices-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 705,
        "src": "/media/amenity-offices-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 705,
        "src": "/media/amenity-offices-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 881,
        "src": "/media/amenity-offices-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 881,
        "src": "/media/amenity-offices-1600.webp"
      },
      {
        "format": "avif",
        "width": 1919,
        "height": 1057,
        "src": "/media/amenity-offices-1919.avif"
      },
      {
        "format": "webp",
        "width": 1919,
        "height": 1057,
        "src": "/media/amenity-offices-1919.webp"
      }
    ]
  },
  "amenity-clubhouse": {
    "id": "amenity-clubhouse",
    "kind": "amenity",
    "alt": "Single-storey clubhouse pavilion with deep timber eaves and open colonnade under bright cloud.",
    "caption": "Clubhouse pavilion — amenity render",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAwCdASoUAAsAPwlwr0+rpqQiMAgBcCEJQBOmUABqUO5yPmrRTtAA/scFiuQIDrWBcwKFWv2F/HHZ/MF0oKxAAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 236,
        "src": "/media/amenity-clubhouse-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 236,
        "src": "/media/amenity-clubhouse-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 360,
        "src": "/media/amenity-clubhouse-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 360,
        "src": "/media/amenity-clubhouse-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 540,
        "src": "/media/amenity-clubhouse-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 540,
        "src": "/media/amenity-clubhouse-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 720,
        "src": "/media/amenity-clubhouse-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 720,
        "src": "/media/amenity-clubhouse-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 900,
        "src": "/media/amenity-clubhouse-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 900,
        "src": "/media/amenity-clubhouse-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1080,
        "src": "/media/amenity-clubhouse-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1080,
        "src": "/media/amenity-clubhouse-1920.webp"
      }
    ]
  },
  "exterior-evening": {
    "id": "exterior-evening",
    "kind": "exterior",
    "alt": "Residences glowing at blue hour, stepping down the hillside among mature trees.",
    "caption": "Residences at blue hour — exterior render",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1083,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAAsAPwlyr0+rpyQiMAgBcCEJZQC7ACHW3GE0TS+NIAD+ohOdX433ZvBW1RmZYpqJlm+X9nhE8vvGfUTXMAAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 237,
        "src": "/media/exterior-evening-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 237,
        "src": "/media/exterior-evening-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 361,
        "src": "/media/exterior-evening-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 361,
        "src": "/media/exterior-evening-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 542,
        "src": "/media/exterior-evening-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 542,
        "src": "/media/exterior-evening-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 722,
        "src": "/media/exterior-evening-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 722,
        "src": "/media/exterior-evening-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 903,
        "src": "/media/exterior-evening-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 903,
        "src": "/media/exterior-evening-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1083,
        "src": "/media/exterior-evening-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1083,
        "src": "/media/exterior-evening-1920.webp"
      }
    ]
  },
  "exterior-walkway": {
    "id": "exterior-walkway",
    "kind": "exterior",
    "alt": "Lantern-lit pedestrian walkway running between residential blocks at night.",
    "caption": "Residential walkway at night — exterior render",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1084,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAAsAPwlwsE+rpqSiMAgBcCEJZQCdAB4+r6gjkBRXAAD+6/42qtB/d/SVvjmOR1sW4zcI6ltfQrbTXp34AAAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 237,
        "src": "/media/exterior-walkway-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 237,
        "src": "/media/exterior-walkway-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 361,
        "src": "/media/exterior-walkway-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 361,
        "src": "/media/exterior-walkway-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 542,
        "src": "/media/exterior-walkway-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 542,
        "src": "/media/exterior-walkway-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 723,
        "src": "/media/exterior-walkway-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 723,
        "src": "/media/exterior-walkway-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 903,
        "src": "/media/exterior-walkway-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 903,
        "src": "/media/exterior-walkway-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1084,
        "src": "/media/exterior-walkway-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1084,
        "src": "/media/exterior-walkway-1920.webp"
      }
    ]
  },
  "exterior-entrance": {
    "id": "exterior-entrance",
    "kind": "exterior",
    "alt": "Arrival colonnade with slatted timber soffits and planting, lit warmly at sunset.",
    "caption": "Arrival colonnade — exterior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwBACdASoUAAsAPwlwr1ArpiQisAgBcCEJQBOmUABd/2b05WAkreYmswAA/qkmiyns+1wl5hGisX2HWfDGWcSacJL5BqPUIAuJuw27PD/AAA==",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 236,
        "src": "/media/exterior-entrance-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 236,
        "src": "/media/exterior-entrance-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 360,
        "src": "/media/exterior-entrance-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 360,
        "src": "/media/exterior-entrance-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 540,
        "src": "/media/exterior-entrance-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 540,
        "src": "/media/exterior-entrance-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 720,
        "src": "/media/exterior-entrance-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 720,
        "src": "/media/exterior-entrance-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 900,
        "src": "/media/exterior-entrance-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 900,
        "src": "/media/exterior-entrance-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1080,
        "src": "/media/exterior-entrance-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1080,
        "src": "/media/exterior-entrance-1920.webp"
      }
    ]
  },
  "exterior-facade": {
    "id": "exterior-facade",
    "kind": "exterior",
    "alt": "Long residential facade with vertical timber fins rising from a landscaped rock garden.",
    "caption": "Timber-finned facade — exterior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1434,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAwCdASoUAA8APwlwsFArpiSisAgBcCEJZQCdAB5n6s+rgxaTAADOHjCSEM6QQ1prb8YbYBv3B0QGc72aYVNFR9ilsVhwAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 314,
        "src": "/media/exterior-facade-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 314,
        "src": "/media/exterior-facade-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 478,
        "src": "/media/exterior-facade-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 478,
        "src": "/media/exterior-facade-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 717,
        "src": "/media/exterior-facade-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 717,
        "src": "/media/exterior-facade-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 956,
        "src": "/media/exterior-facade-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 956,
        "src": "/media/exterior-facade-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 1195,
        "src": "/media/exterior-facade-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 1195,
        "src": "/media/exterior-facade-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1434,
        "src": "/media/exterior-facade-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1434,
        "src": "/media/exterior-facade-1920.webp"
      }
    ]
  },
  "exterior-sunset": {
    "id": "exterior-sunset",
    "kind": "exterior",
    "alt": "Stepped residences catching an orange sunset across the wooded ridge.",
    "caption": "Stepped residences at sunset — exterior render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1080,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUAAsAPwlysVArpqSisAgBcCEJQBOgA3EfK2hcWzgyJQAA/HHok9g5lHDJZmZP4X2FkUSpHbALId1/tnWmHBkCSdtgAA==",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 236,
        "src": "/media/exterior-sunset-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 236,
        "src": "/media/exterior-sunset-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 360,
        "src": "/media/exterior-sunset-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 360,
        "src": "/media/exterior-sunset-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 540,
        "src": "/media/exterior-sunset-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 540,
        "src": "/media/exterior-sunset-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 720,
        "src": "/media/exterior-sunset-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 720,
        "src": "/media/exterior-sunset-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 900,
        "src": "/media/exterior-sunset-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 900,
        "src": "/media/exterior-sunset-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1080,
        "src": "/media/exterior-sunset-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1080,
        "src": "/media/exterior-sunset-1920.webp"
      }
    ]
  },
  "location-aerial": {
    "id": "location-aerial",
    "kind": "location",
    "alt": "Wide dusk view across the Tbilisi valley with the Mira Verde community in the foreground and the city lights beyond.",
    "caption": "Mira Verde above the Tbilisi valley — location render",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 2100,
    "height": 1181,
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQBACdASoUAAsAPwl0s1CrpySisAgBcCEJYwCdIHADFFzXgezL/Z2uwAD8bj95kGjbBQMJRGXORkpROsCuc8+4pgQtYAAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 236,
        "src": "/media/location-aerial-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 236,
        "src": "/media/location-aerial-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 360,
        "src": "/media/location-aerial-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 360,
        "src": "/media/location-aerial-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 540,
        "src": "/media/location-aerial-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 540,
        "src": "/media/location-aerial-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 720,
        "src": "/media/location-aerial-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 720,
        "src": "/media/location-aerial-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 900,
        "src": "/media/location-aerial-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 900,
        "src": "/media/location-aerial-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1080,
        "src": "/media/location-aerial-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1080,
        "src": "/media/location-aerial-1920.webp"
      },
      {
        "format": "avif",
        "width": 2100,
        "height": 1181,
        "src": "/media/location-aerial-2100.avif"
      },
      {
        "format": "webp",
        "width": 2100,
        "height": 1181,
        "src": "/media/location-aerial-2100.webp"
      }
    ]
  },
  "location-masterplan": {
    "id": "location-masterplan",
    "kind": "masterplan",
    "alt": "Annotated aerial masterplan diagram showing the Trussardi residential towers, branded apartments, townhouses, five-star hotel and school across the Mira Verde site.",
    "caption": "Mira Verde masterplan — annotated site diagram",
    "source": "https://mira-verde.com/",
    "priority": false,
    "gallery": true,
    "width": 2400,
    "height": 1234,
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUAAoAPwlyr1ArpyQisAgBcCEJZQC/OB8rE2LzBAAA/svn1DP5PnHmuJI5TyM1Prqw1SZAAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 216,
        "src": "/media/location-masterplan-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 216,
        "src": "/media/location-masterplan-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 329,
        "src": "/media/location-masterplan-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 329,
        "src": "/media/location-masterplan-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 494,
        "src": "/media/location-masterplan-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 494,
        "src": "/media/location-masterplan-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 658,
        "src": "/media/location-masterplan-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 658,
        "src": "/media/location-masterplan-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 823,
        "src": "/media/location-masterplan-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 823,
        "src": "/media/location-masterplan-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 987,
        "src": "/media/location-masterplan-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 987,
        "src": "/media/location-masterplan-1920.webp"
      },
      {
        "format": "avif",
        "width": 2400,
        "height": 1234,
        "src": "/media/location-masterplan-2400.avif"
      },
      {
        "format": "webp",
        "width": 2400,
        "height": 1234,
        "src": "/media/location-masterplan-2400.webp"
      }
    ]
  },
  "location-tbilisi-street": {
    "id": "location-tbilisi-street",
    "kind": "location",
    "alt": "Tree-lined Tbilisi street with a Georgian flag on a classical stone facade.",
    "caption": "Central Tbilisi — location photograph",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 1280,
    "height": 1920,
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwBACdASoUAB4APwlyrE+rpyQiMBgMAXAhCWUAuwAKJNinf5PvU23ZUrPW/LFZTuwA+dOH9Kxwukx2Dlye05S6PI9tu6HVlO2vxgDQrTSbL3jg61ckjNaMlrCDPaoC0VUnGAAA",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 630,
        "src": "/media/location-tbilisi-street-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 630,
        "src": "/media/location-tbilisi-street-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 960,
        "src": "/media/location-tbilisi-street-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 960,
        "src": "/media/location-tbilisi-street-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 1440,
        "src": "/media/location-tbilisi-street-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 1440,
        "src": "/media/location-tbilisi-street-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 1920,
        "src": "/media/location-tbilisi-street-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 1920,
        "src": "/media/location-tbilisi-street-1280.webp"
      }
    ]
  },
  "location-tbilisi-city": {
    "id": "location-tbilisi-city",
    "kind": "location",
    "alt": "Traffic moving along a tree-lined Tbilisi boulevard past a contemporary canopied building.",
    "caption": "Tbilisi boulevard — location photograph",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": true,
    "width": 1920,
    "height": 1280,
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoUAA0APwlur0+rpiQiMAgBcCEJZwDDNB6WBnpXRbECgAD+mR425VrnO7taHU43DDoivzZRXO6Su9OgAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 280,
        "src": "/media/location-tbilisi-city-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 280,
        "src": "/media/location-tbilisi-city-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 427,
        "src": "/media/location-tbilisi-city-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 427,
        "src": "/media/location-tbilisi-city-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 640,
        "src": "/media/location-tbilisi-city-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 640,
        "src": "/media/location-tbilisi-city-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 853,
        "src": "/media/location-tbilisi-city-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 853,
        "src": "/media/location-tbilisi-city-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 1067,
        "src": "/media/location-tbilisi-city-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 1067,
        "src": "/media/location-tbilisi-city-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1280,
        "src": "/media/location-tbilisi-city-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1280,
        "src": "/media/location-tbilisi-city-1920.webp"
      }
    ]
  },
  "plan-studio": {
    "id": "plan-studio",
    "kind": "plan",
    "alt": "Studio floor plan showing a single bedroom-living space, bathroom, kitchen run and balcony.",
    "caption": "Studio — indicative floor plan",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": false,
    "width": 695,
    "height": 395,
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAwCdASoUAAsAPwlyr0+rpyQiMAgBcCEJZwDA3CPTZN0RA+UpEAAA/tV3cI4l0I49kXmEtED4S36d882gAA==",
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "height": 364,
        "src": "/media/plan-studio-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 364,
        "src": "/media/plan-studio-640.webp"
      },
      {
        "format": "avif",
        "width": 695,
        "height": 395,
        "src": "/media/plan-studio-695.avif"
      },
      {
        "format": "webp",
        "width": 695,
        "height": 395,
        "src": "/media/plan-studio-695.webp"
      }
    ]
  },
  "plan-1br": {
    "id": "plan-1br",
    "kind": "plan",
    "alt": "One-bedroom floor plan showing a separate bedroom, living room, bathroom, laundry and balcony.",
    "caption": "One-bedroom — indicative floor plan",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": false,
    "width": 627,
    "height": 552,
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABQBACdASoUABIAPu1kp0+ppaOiN+gBMB2JZwAAiHDcczIEDD7Kr/REMBcAAP7UAkoM4fdBOijkBkvugz6NvRkCjNDuaCLxHb4TTHAA",
    "variants": [
      {
        "format": "avif",
        "width": 627,
        "height": 552,
        "src": "/media/plan-1br-627.avif"
      },
      {
        "format": "webp",
        "width": 627,
        "height": 552,
        "src": "/media/plan-1br-627.webp"
      }
    ]
  },
  "plan-2br": {
    "id": "plan-2br",
    "kind": "plan",
    "alt": "Two-bedroom floor plan showing two bedrooms, two bathrooms, living room, laundry and balcony area.",
    "caption": "Two-bedroom — indicative floor plan",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": false,
    "width": 779,
    "height": 503,
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUAA0APwlyr0+rpyQiMAgBcCEJZwDImCHR7xRhSRoAAP7Eim2r8q/pdBIqeLDboaPzpAsAAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 640,
        "height": 413,
        "src": "/media/plan-2br-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 413,
        "src": "/media/plan-2br-640.webp"
      },
      {
        "format": "avif",
        "width": 779,
        "height": 503,
        "src": "/media/plan-2br-779.avif"
      },
      {
        "format": "webp",
        "width": 779,
        "height": 503,
        "src": "/media/plan-2br-779.webp"
      }
    ]
  },
  "closing": {
    "id": "closing",
    "kind": "exterior",
    "alt": "The Mira Verde community lit against a deep blue night sky on the forested hillside.",
    "caption": "Mira Verde at night — exterior render",
    "source": "https://trussardi-residences.ge/",
    "priority": false,
    "gallery": false,
    "width": 1920,
    "height": 1072,
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoUAAsAPwlwr1ArpiQisAgBcCEJZQCdACHcGZC0/SIzkhAA/uQRhitN9E9h1Oi6DucgKziOQGlZKve/3/4MZAFgAAA=",
    "variants": [
      {
        "format": "avif",
        "width": 420,
        "height": 235,
        "src": "/media/closing-420.avif"
      },
      {
        "format": "webp",
        "width": 420,
        "height": 235,
        "src": "/media/closing-420.webp"
      },
      {
        "format": "avif",
        "width": 640,
        "height": 357,
        "src": "/media/closing-640.avif"
      },
      {
        "format": "webp",
        "width": 640,
        "height": 357,
        "src": "/media/closing-640.webp"
      },
      {
        "format": "avif",
        "width": 960,
        "height": 536,
        "src": "/media/closing-960.avif"
      },
      {
        "format": "webp",
        "width": 960,
        "height": 536,
        "src": "/media/closing-960.webp"
      },
      {
        "format": "avif",
        "width": 1280,
        "height": 715,
        "src": "/media/closing-1280.avif"
      },
      {
        "format": "webp",
        "width": 1280,
        "height": 715,
        "src": "/media/closing-1280.webp"
      },
      {
        "format": "avif",
        "width": 1600,
        "height": 893,
        "src": "/media/closing-1600.avif"
      },
      {
        "format": "webp",
        "width": 1600,
        "height": 893,
        "src": "/media/closing-1600.webp"
      },
      {
        "format": "avif",
        "width": 1920,
        "height": 1072,
        "src": "/media/closing-1920.avif"
      },
      {
        "format": "webp",
        "width": 1920,
        "height": 1072,
        "src": "/media/closing-1920.webp"
      }
    ]
  }
} as const;

export const GALLERY_MEDIA: readonly MediaAsset[] = [
  MEDIA['overview-aerial'],
  MEDIA['interior-living'],
  MEDIA['interior-bedroom'],
  MEDIA['interior-lounge'],
  MEDIA['interior-kitchen'],
  MEDIA['amenity-golf'],
  MEDIA['amenity-retail'],
  MEDIA['amenity-wellness'],
  MEDIA['amenity-offices'],
  MEDIA['amenity-clubhouse'],
  MEDIA['exterior-evening'],
  MEDIA['exterior-walkway'],
  MEDIA['exterior-entrance'],
  MEDIA['exterior-facade'],
  MEDIA['exterior-sunset'],
  MEDIA['location-aerial'],
  MEDIA['location-masterplan'],
  MEDIA['location-tbilisi-street'],
  MEDIA['location-tbilisi-city'],
];
